# Generated by Django 3.1.3 on 2020-12-30 16:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='متن جواب')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('author', models.ForeignKey(default='accounts.User', on_delete=django.db.models.deletion.CASCADE, related_name='answer_rel', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جواب',
                'verbose_name_plural': 'جواب ها',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=90, unique=True, verbose_name='لینک یکتا')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی ها',
                'db_table': 'category',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('other', 'دیگر موارد'), ('politic', 'مورد سیاسی'), ('swearing', 'الفاظ رکیک'), ('non-relative-tag', 'برچسب غیر مربوط')], default='other', max_length=20, verbose_name='عنوان گزارش')),
                ('additional_message', models.TextField(max_length=150, verbose_name='توضیحات بیشتر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد گزارش')),
                ('reported_question', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='پاسخ مشکلدار')),
                ('user', models.ForeignKey(default='accounts.User', on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش دهنده')),
            ],
            options={
                'verbose_name': 'تخلفات',
                'verbose_name_plural': 'تخلفات',
                'db_table': 'report',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان پرسش')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن پرسش')),
                ('slug', models.SlugField(blank=True, max_length=90, null=True, unique=True, verbose_name='لینک یکتا')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('num_of_views', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='questions.category', verbose_name='دسته بندی')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like_questions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, default=None, related_name='tag_questions', to='questions.Tag', verbose_name='برچسب')),
                ('user', models.ForeignKey(default='accounts.User', on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to=settings.AUTH_USER_MODEL, verbose_name='پرسشگر')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
                'db_table': 'question',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='related_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='questions.question', verbose_name='سوال مربوطه'),
        ),
    ]
