# Generated by Django 3.1.3 on 2020-12-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_of_views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
