# Generated by Django 3.1.3 on 2020-12-28 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
