# Generated by Django 3.1.3 on 2020-11-30 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=90, unique=True, verbose_name='لینک یکتا')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی ها',
                'db_table': 'category',
                'ordering': ('date_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('date_created',), 'verbose_name': 'سوال', 'verbose_name_plural': 'سوال ها'},
        ),
        migrations.AddField(
            model_name='question',
            name='num_of_reports',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=None, max_length=90, unique=True, verbose_name='لینک یکتا'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=120, verbose_name='عنوان پرسش'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='پرسشگر'),
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='questions.Category', verbose_name='دسته بندی'),
        ),
    ]
