# Generated by Django 3.1.3 on 2020-12-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_answer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='پاسخ مشکلدار'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_question',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='سوال مشکلدار'),
        ),
    ]
