# Generated by Django 3.1.3 on 2020-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201130_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=1200, verbose_name='متن پرسش'),
        ),
    ]
