# Generated by Django 3.1.3 on 2020-12-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201230_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='سوال مشکلدار'),
        ),
    ]
