# Generated by Django 3.1.3 on 2020-12-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201130_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_of_likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_of_reports',
        ),
    ]
