# Generated by Django 3.1.3 on 2021-01-02 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20201230_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('other', 'دیگر موارد'), ('politic', 'مورد سیاسی'), ('swearing', 'الفاظ رکیک'), ('non-relative-tag', 'برچسب غیر مربوط')], default='other', max_length=20, verbose_name='عنوان گزارش')),
                ('additional_message', models.TextField(max_length=150, verbose_name='توضیحات بیشتر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد گزارش')),
                ('reported_answer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='پاسخ مشکلدار')),
                ('user', models.ForeignKey(default='accounts.User', on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش دهنده')),
            ],
            options={
                'verbose_name': 'تخلفات در جواب',
                'verbose_name_plural': 'تخلفات در جواب ها',
                'db_table': 'AnswerReport',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('other', 'دیگر موارد'), ('politic', 'مورد سیاسی'), ('swearing', 'الفاظ رکیک'), ('non-relative-tag', 'برچسب غیر مربوط')], default='other', max_length=20, verbose_name='عنوان گزارش')),
                ('additional_message', models.TextField(max_length=150, verbose_name='توضیحات بیشتر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد گزارش')),
                ('reported_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='سوال مشکلدار')),
                ('user', models.ForeignKey(default='accounts.User', on_delete=django.db.models.deletion.CASCADE, related_name='user_question_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش دهنده')),
            ],
            options={
                'verbose_name': 'تخلفات در سوال',
                'verbose_name_plural': 'تخلفات در سوالات',
                'db_table': 'QuestionReport',
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
