# Generated by Django 3.1.3 on 2021-01-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210102_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب'),
        ),
    ]
