# Generated by Django 3.1.3 on 2020-12-10 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20201210_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن پرسش'),
        ),
    ]
