# Generated by Django 3.1.3 on 2021-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210103_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='برچسب'),
            preserve_default=False,
        ),
    ]
