# Generated by Django 3.1.3 on 2021-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210103_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreport',
            name='additional_message',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='توضیحات بیشتر'),
        ),
    ]
