# Generated by Django 3.1.3 on 2021-02-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210209_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='متن اعلامیه')),
                ('type', models.CharField(choices=[('question liked', 'لایک پرسش'), ('answer liked', 'لایک پاسخ'), ('question answered', 'پاسخ به سوال')], default='', max_length=30, verbose_name='نوع اعلامیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
