# Generated by Django 3.1.3 on 2021-02-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210212_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier_notifs', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده اعلامیه'),
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_notifications', to='accounts.user', verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
