# Generated by Django 3.1.3 on 2021-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210212_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
